### ISSUE TITLE
운영위원회의 탄핵 절차 추가

### ISSUE THREAD

**Issue by eddie878** [maeng22/shangrila-constitution#11]
운영위원회 그리고 총괄부는 동아리를 운영하는데 있어서 많은 권한을 가지고 있습니다. 이러한 부분에 있어서 운영위원이 커다란 잘못이나 결격사유가 발생하였을 경우 탄핵을 통해 그 자리에서 내려올 수 있게하는 장치가 필요로 합니다. 현재 회칙에서는 임시 회의가 그 역할의 수행이 가능하지만 임시 회의의 경우 그 권한이 매우 크기에 한번 염에 있어서 조심스러워야 합니다.
이러한 이유로 탄핵 절차는 동아리원이 운영위원회를 견제하는 장치로써 필수적이라고 생각합니다.

**Comment by codename-whiteroom** [comment]
탄핵 절차는 개정안에도 존재합니다.
현재 개정안 회칙 제 3장 2조를 다시 확인해 주시길 바랍니다.

**Comment by codename-whiteroom** [comment]
재확인 결과, 임원진이 작성 중 누락한 것으로 보입니다.
반드시 추가되어야 하는 사안이 맞다고 생각합니다. 이에 대해서는 가능한 빠르게 추가해 두겠습니다.

**Comment by maeng22** [comment]
죄송합니다, 제가 Markdown으로 옮길 때 깜빡한 것 같네요. d6bbaa0e6adbd82e5d90382f7561e05606a032e6 에서 관련 내용 옮겨 두었습니다.

이걸로 문제가 해결됐다면 이 이슈는 닫아도 괜찮을까요?
