### ISSUE TITLE
운영위원회 구조 변경

### ISSUE THREAD

**Issue by codename-whiteroom** [maeng22/shangrila-constitution#6]
신설한 제도에서 운영위원회는 크게 총괄부, 관리부, 홍보부, 그리고 편집부로 나뉘었습니다.

그러나 0912 정모에서 나온 신규 의견으로써 해당 부서의 분할이 불분명하다는 의견이 나왔습니다.

이에 따라 아래와 같은 새로운 운영위원회의 분류를 제안합니다.

1. 전체 운영위원회는 총괄부, 기획부, 총무부, 기록부, 그리고 관리부로 나뉜다.
2. 기획부의 장은 기획부장이라 명칭한다.
3. 총무부의 장은 총무라 명칭한다.
4. 기록부의 장은 서기라 명칭한다.
5. 관리부의 장은 관리부장이라 명칭한다.
6. 기획부장, 총무, 서기, 관리부장은 총괄부에 소속되는 것으로 정의한다.
7. 총괄부의 장을 회장이라 명칭하며, 총괄부에 소속되어 있는 인원을 '임원'으로 정의한다.

각 자리의 인원은 기존과 동일하게 유지하며, 후계자 양성, 업무 분할 및 만일의 사태를 대비하여 각 부에는 최소 한 명 이상의 부원을 배치하도록 하고 싶습니다.
운영위원회의 장들은 기존의 방식과 똑같이 투표로 결정하며, 자신의 관할 부서에 속하는 사람들은 장이 선출하는 방식으로 제안합니다.
이와 같이 만들 경우, 인수인계에 있어 문제의 소지가 줄어들 것이며, 업무량 완화를 꾀할 수도 있을 것이라 생각합니다.

최종적으로, 관리부와 기획부의 경우 관례적으로 3학년 이상을 앉힌다는 발언을 기억합니다.
이와 같은 경우, 회칙에 언급할 만한 중요사항은 아니라고 판단하며, 만일 2학년이 관리부장이나 기획부장이 되어 불안한 점이 있다면 각 부원을 더 고학년의 인원으로 뽑는 것 또한 고려해볼 만 하다고 생각합니다.

**Comment by maeng22** [comment]
#2 와 관련이 있는 안건이네요. 이슈 중복을 막기 위해 여기는 닫고 #2 에서 다시 논의를 해야 할까요? 아니면 기존의 이슈와는 다른 안건이 있으신 건가요?

**Comment by codename-whiteroom** [comment]
2의 경우, 이미 정모에서 한번 이야기를 나눈 안건이고
그 당시 이와 같이 제도를 개편하는 방안에 대해 논의가 나왔던 것이니
여기에서 의논하는게 더 적절하다고 생각합니다

**Comment by maeng22** [comment]
#2 에서는 저번 주에 임원진이 제안한 것 이외에도 운영위원회 구조 변경에 대한 포괄적인 의논을 맡는 이슈이기 때문에, #2 에서 논의하는 게 더 적절하다고 생각이 드네요. 중복을 막기 위해 이 이슈를 닫아도 괜찮을까요?

**Comment by codename-whiteroom** [comment]
좋습니다.
#2에 복사해 두겠습니다.
